package com.spring.dyndb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Builder;
import lombok.Data;

@Data
@Builder
@DynamoDBTable(tableName = "Employees")
public class Employee {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;

	private String name;

	private String email;

}
